// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterWorkerRequest {
    /// Unique worker identifier. If empty, coordinator will assign one.
    #[prost(string, tag = "1")]
    pub worker_id: ::prost::alloc::string::String,
    /// Job identifier to group workers.
    #[prost(string, tag = "2")]
    pub job_id: ::prost::alloc::string::String,
    /// Worker capabilities for assignment decisions.
    #[prost(message, optional, tag = "3")]
    pub capabilities: ::core::option::Option<WorkerCapabilities>,
    /// Optional hostname for locality-aware scheduling.
    #[prost(string, tag = "4")]
    pub hostname: ::prost::alloc::string::String,
    /// Optional tags for filtering/grouping.
    #[prost(map = "string, string", tag = "5")]
    pub tags: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WorkerCapabilities {
    /// Number of GPUs available.
    #[prost(uint32, tag = "1")]
    pub gpu_count: u32,
    /// Total memory in bytes.
    #[prost(uint64, tag = "2")]
    pub memory_bytes: u64,
    /// Whether worker can access local storage.
    #[prost(bool, tag = "3")]
    pub has_local_storage: bool,
    /// Storage paths accessible by this worker.
    #[prost(string, repeated, tag = "4")]
    pub accessible_paths: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Custom capability flags.
    #[prost(map = "string, string", tag = "5")]
    pub custom: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterWorkerResponse {
    /// Assigned worker configuration.
    #[prost(message, optional, tag = "1")]
    pub config: ::core::option::Option<WorkerConfig>,
    /// Whether this is a reconnection of a previously registered worker.
    #[prost(bool, tag = "2")]
    pub reconnected: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WorkerConfig {
    /// Confirmed worker ID (assigned if not provided in request).
    #[prost(string, tag = "1")]
    pub worker_id: ::prost::alloc::string::String,
    /// Worker index in the job (0-based).
    #[prost(uint32, tag = "2")]
    pub worker_index: u32,
    /// Total number of workers in the job.
    #[prost(uint32, tag = "3")]
    pub total_workers: u32,
    /// Job configuration.
    #[prost(string, tag = "4")]
    pub job_id: ::prost::alloc::string::String,
    /// Recommended heartbeat interval in milliseconds.
    #[prost(uint64, tag = "5")]
    pub heartbeat_interval_ms: u64,
    /// Session token for authentication of subsequent requests.
    #[prost(string, tag = "6")]
    pub session_token: ::prost::alloc::string::String,
    /// Coordinator-assigned settings.
    #[prost(map = "string, string", tag = "7")]
    pub settings: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnregisterWorkerRequest {
    #[prost(string, tag = "1")]
    pub worker_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub session_token: ::prost::alloc::string::String,
    /// Reason for unregistration.
    #[prost(string, tag = "3")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct UnregisterWorkerResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetShardAssignmentRequest {
    #[prost(string, tag = "1")]
    pub worker_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub session_token: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub dataset_id: ::prost::alloc::string::String,
    /// Total number of shards in the dataset.
    #[prost(uint32, tag = "4")]
    pub total_shards: u32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetShardAssignmentResponse {
    /// Assigned shard ranges for this worker.
    #[prost(message, repeated, tag = "1")]
    pub shard_ranges: ::prost::alloc::vec::Vec<ShardRange>,
    /// Assignment version (for detecting stale assignments).
    #[prost(uint64, tag = "2")]
    pub assignment_version: u64,
    /// Strategy used for assignment.
    #[prost(enumeration = "ShardStrategy", tag = "3")]
    pub strategy: i32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ShardRange {
    /// Start shard ID (inclusive).
    #[prost(uint32, tag = "1")]
    pub start_shard: u32,
    /// End shard ID (exclusive).
    #[prost(uint32, tag = "2")]
    pub end_shard: u32,
    /// Optional priority for processing order.
    #[prost(uint32, tag = "3")]
    pub priority: u32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProgressReport {
    #[prost(string, tag = "1")]
    pub worker_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub session_token: ::prost::alloc::string::String,
    /// Training step/iteration.
    #[prost(uint64, tag = "3")]
    pub step: u64,
    /// Samples processed in this report period.
    #[prost(uint64, tag = "4")]
    pub samples_processed: u64,
    /// Current loss value (optional).
    #[prost(double, optional, tag = "5")]
    pub loss: ::core::option::Option<f64>,
    /// Custom metrics.
    #[prost(map = "string, double", tag = "6")]
    pub metrics: ::std::collections::HashMap<::prost::alloc::string::String, f64>,
    /// Timestamp of this report (Unix millis).
    #[prost(int64, tag = "7")]
    pub timestamp_ms: i64,
    /// Current dataset and shard being processed.
    #[prost(string, tag = "8")]
    pub current_dataset: ::prost::alloc::string::String,
    #[prost(uint32, tag = "9")]
    pub current_shard: u32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ProgressAck {
    /// Whether to continue training.
    #[prost(bool, tag = "1")]
    pub continue_training: bool,
    /// Optional command from coordinator.
    #[prost(enumeration = "CoordinatorCommand", tag = "2")]
    pub command: i32,
    /// Server timestamp for latency calculation.
    #[prost(int64, tag = "3")]
    pub server_timestamp_ms: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HeartbeatRequest {
    #[prost(string, tag = "1")]
    pub worker_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub session_token: ::prost::alloc::string::String,
    /// Current worker status.
    #[prost(enumeration = "WorkerStatus", tag = "3")]
    pub status: i32,
    /// Current training step.
    #[prost(uint64, tag = "4")]
    pub step: u64,
    /// Memory usage in bytes.
    #[prost(uint64, tag = "5")]
    pub memory_used_bytes: u64,
    /// GPU utilization (0.0-1.0).
    #[prost(double, optional, tag = "6")]
    pub gpu_utilization: ::core::option::Option<f64>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HeartbeatResponse {
    /// Whether the worker is still registered.
    #[prost(bool, tag = "1")]
    pub registered: bool,
    /// Optional command from coordinator.
    #[prost(enumeration = "CoordinatorCommand", tag = "2")]
    pub command: i32,
    /// If command is CHECKPOINT, the checkpoint plan.
    #[prost(message, optional, tag = "3")]
    pub checkpoint_plan: ::core::option::Option<CheckpointPlan>,
    /// Current leader worker ID (for distributed operations).
    #[prost(string, tag = "4")]
    pub leader_worker_id: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InitiateCheckpointRequest {
    #[prost(string, tag = "1")]
    pub worker_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub session_token: ::prost::alloc::string::String,
    /// Checkpoint name/identifier.
    #[prost(string, tag = "3")]
    pub checkpoint_name: ::prost::alloc::string::String,
    /// Current training step.
    #[prost(uint64, tag = "4")]
    pub step: u64,
    /// Optional metadata to include in checkpoint.
    #[prost(map = "string, string", tag = "5")]
    pub metadata: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CheckpointPlan {
    /// Unique checkpoint operation ID.
    #[prost(string, tag = "1")]
    pub checkpoint_id: ::prost::alloc::string::String,
    /// Checkpoint name provided in request.
    #[prost(string, tag = "2")]
    pub checkpoint_name: ::prost::alloc::string::String,
    /// Step at which checkpoint is being taken.
    #[prost(uint64, tag = "3")]
    pub step: u64,
    /// Base path for checkpoint shards.
    #[prost(string, tag = "4")]
    pub base_path: ::prost::alloc::string::String,
    /// Assignment of shards to workers.
    #[prost(message, repeated, tag = "5")]
    pub assignments: ::prost::alloc::vec::Vec<WorkerCheckpointAssignment>,
    /// Deadline for completing checkpoint (Unix millis).
    #[prost(int64, tag = "6")]
    pub deadline_ms: i64,
    /// Compression to use.
    #[prost(string, tag = "7")]
    pub compression: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WorkerCheckpointAssignment {
    #[prost(string, tag = "1")]
    pub worker_id: ::prost::alloc::string::String,
    /// Path where this worker should write its checkpoint shard.
    #[prost(string, tag = "2")]
    pub shard_path: ::prost::alloc::string::String,
    /// Shard index for this worker.
    #[prost(uint32, tag = "3")]
    pub shard_index: u32,
    /// Keys this worker is responsible for checkpointing.
    #[prost(string, repeated, tag = "4")]
    pub assigned_keys: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CheckpointShardConfirmation {
    #[prost(string, tag = "1")]
    pub worker_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub session_token: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub checkpoint_id: ::prost::alloc::string::String,
    /// Path where shard was written.
    #[prost(string, tag = "4")]
    pub shard_path: ::prost::alloc::string::String,
    /// Shard index.
    #[prost(uint32, tag = "5")]
    pub shard_index: u32,
    /// Size in bytes.
    #[prost(uint64, tag = "6")]
    pub size_bytes: u64,
    /// Checksum (xxhash64 of compressed data).
    #[prost(uint64, tag = "7")]
    pub checksum: u64,
    /// Whether write succeeded.
    #[prost(bool, tag = "8")]
    pub success: bool,
    /// Error message if failed.
    #[prost(string, tag = "9")]
    pub error_message: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CheckpointShardAck {
    #[prost(bool, tag = "1")]
    pub accepted: bool,
    /// Number of workers that have confirmed.
    #[prost(uint32, tag = "2")]
    pub confirmed_count: u32,
    /// Total workers expected.
    #[prost(uint32, tag = "3")]
    pub total_workers: u32,
    /// Whether checkpoint is complete.
    #[prost(bool, tag = "4")]
    pub checkpoint_complete: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetCheckpointStatusRequest {
    #[prost(string, tag = "1")]
    pub checkpoint_id: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CheckpointStatus {
    #[prost(string, tag = "1")]
    pub checkpoint_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub checkpoint_name: ::prost::alloc::string::String,
    #[prost(enumeration = "CheckpointState", tag = "3")]
    pub state: i32,
    /// Workers that have confirmed.
    #[prost(string, repeated, tag = "4")]
    pub confirmed_workers: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Workers still pending.
    #[prost(string, repeated, tag = "5")]
    pub pending_workers: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// If complete, the manifest.
    #[prost(message, optional, tag = "6")]
    pub manifest: ::core::option::Option<CheckpointManifest>,
    /// Error message if failed.
    #[prost(string, tag = "7")]
    pub error_message: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CheckpointManifest {
    /// Checkpoint identifier.
    #[prost(string, tag = "1")]
    pub checkpoint_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub checkpoint_name: ::prost::alloc::string::String,
    /// Training step.
    #[prost(uint64, tag = "3")]
    pub step: u64,
    /// Creation timestamp (Unix millis).
    #[prost(int64, tag = "4")]
    pub created_at_ms: i64,
    /// Individual shard information.
    #[prost(message, repeated, tag = "5")]
    pub shards: ::prost::alloc::vec::Vec<CheckpointShardInfo>,
    /// Total size across all shards.
    #[prost(uint64, tag = "6")]
    pub total_size_bytes: u64,
    /// Total checksum (combined hash of all shard checksums).
    #[prost(uint64, tag = "7")]
    pub total_checksum: u64,
    /// User-provided metadata.
    #[prost(map = "string, string", tag = "8")]
    pub metadata: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// Number of workers that participated.
    #[prost(uint32, tag = "9")]
    pub worker_count: u32,
    /// Format version.
    #[prost(uint32, tag = "10")]
    pub format_version: u32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CheckpointShardInfo {
    #[prost(uint32, tag = "1")]
    pub shard_index: u32,
    #[prost(string, tag = "2")]
    pub worker_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub path: ::prost::alloc::string::String,
    #[prost(uint64, tag = "4")]
    pub size_bytes: u64,
    #[prost(uint64, tag = "5")]
    pub checksum: u64,
    #[prost(string, repeated, tag = "6")]
    pub keys: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetWorkerStatusRequest {
    /// If empty, returns all workers in the job.
    #[prost(string, tag = "1")]
    pub worker_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub job_id: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WorkerStatusResponse {
    #[prost(message, repeated, tag = "1")]
    pub workers: ::prost::alloc::vec::Vec<WorkerInfo>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WorkerInfo {
    #[prost(string, tag = "1")]
    pub worker_id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub worker_index: u32,
    #[prost(enumeration = "WorkerStatus", tag = "3")]
    pub status: i32,
    /// Last heartbeat timestamp (Unix millis).
    #[prost(int64, tag = "4")]
    pub last_heartbeat_ms: i64,
    /// Current training step.
    #[prost(uint64, tag = "5")]
    pub step: u64,
    /// Assigned shard ranges by dataset.
    #[prost(map = "string, message", tag = "6")]
    pub assignments: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ShardAssignment,
    >,
    /// Worker capabilities.
    #[prost(message, optional, tag = "7")]
    pub capabilities: ::core::option::Option<WorkerCapabilities>,
    /// Whether worker is considered healthy.
    #[prost(bool, tag = "8")]
    pub healthy: bool,
    /// Hostname.
    #[prost(string, tag = "9")]
    pub hostname: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ShardAssignment {
    #[prost(message, repeated, tag = "1")]
    pub ranges: ::prost::alloc::vec::Vec<ShardRange>,
    #[prost(uint64, tag = "2")]
    pub version: u64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ShardStrategy {
    Unspecified = 0,
    /// Fixed assignment based on worker index.
    Static = 1,
    /// Dynamic rebalancing as workers join/leave.
    Dynamic = 2,
    /// Prefer shards on local storage.
    LocalityAware = 3,
}
impl ShardStrategy {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "SHARD_STRATEGY_UNSPECIFIED",
            Self::Static => "SHARD_STRATEGY_STATIC",
            Self::Dynamic => "SHARD_STRATEGY_DYNAMIC",
            Self::LocalityAware => "SHARD_STRATEGY_LOCALITY_AWARE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SHARD_STRATEGY_UNSPECIFIED" => Some(Self::Unspecified),
            "SHARD_STRATEGY_STATIC" => Some(Self::Static),
            "SHARD_STRATEGY_DYNAMIC" => Some(Self::Dynamic),
            "SHARD_STRATEGY_LOCALITY_AWARE" => Some(Self::LocalityAware),
            _ => None,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CoordinatorCommand {
    Unspecified = 0,
    /// No action needed.
    Continue = 1,
    /// Pause and wait for further instructions.
    Pause = 2,
    /// Initiate checkpoint now.
    Checkpoint = 3,
    /// Gracefully stop training.
    Stop = 4,
    /// Refresh shard assignments.
    RefreshAssignments = 5,
}
impl CoordinatorCommand {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "COORDINATOR_COMMAND_UNSPECIFIED",
            Self::Continue => "COORDINATOR_COMMAND_CONTINUE",
            Self::Pause => "COORDINATOR_COMMAND_PAUSE",
            Self::Checkpoint => "COORDINATOR_COMMAND_CHECKPOINT",
            Self::Stop => "COORDINATOR_COMMAND_STOP",
            Self::RefreshAssignments => "COORDINATOR_COMMAND_REFRESH_ASSIGNMENTS",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "COORDINATOR_COMMAND_UNSPECIFIED" => Some(Self::Unspecified),
            "COORDINATOR_COMMAND_CONTINUE" => Some(Self::Continue),
            "COORDINATOR_COMMAND_PAUSE" => Some(Self::Pause),
            "COORDINATOR_COMMAND_CHECKPOINT" => Some(Self::Checkpoint),
            "COORDINATOR_COMMAND_STOP" => Some(Self::Stop),
            "COORDINATOR_COMMAND_REFRESH_ASSIGNMENTS" => Some(Self::RefreshAssignments),
            _ => None,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum WorkerStatus {
    Unspecified = 0,
    /// Worker is idle, waiting for work.
    Idle = 1,
    /// Worker is actively training.
    Training = 2,
    /// Worker is writing checkpoint.
    Checkpointing = 3,
    /// Worker is loading data.
    Loading = 4,
    /// Worker encountered an error.
    Error = 5,
    /// Worker is shutting down.
    ShuttingDown = 6,
}
impl WorkerStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "WORKER_STATUS_UNSPECIFIED",
            Self::Idle => "WORKER_STATUS_IDLE",
            Self::Training => "WORKER_STATUS_TRAINING",
            Self::Checkpointing => "WORKER_STATUS_CHECKPOINTING",
            Self::Loading => "WORKER_STATUS_LOADING",
            Self::Error => "WORKER_STATUS_ERROR",
            Self::ShuttingDown => "WORKER_STATUS_SHUTTING_DOWN",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "WORKER_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "WORKER_STATUS_IDLE" => Some(Self::Idle),
            "WORKER_STATUS_TRAINING" => Some(Self::Training),
            "WORKER_STATUS_CHECKPOINTING" => Some(Self::Checkpointing),
            "WORKER_STATUS_LOADING" => Some(Self::Loading),
            "WORKER_STATUS_ERROR" => Some(Self::Error),
            "WORKER_STATUS_SHUTTING_DOWN" => Some(Self::ShuttingDown),
            _ => None,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CheckpointState {
    Unspecified = 0,
    /// Checkpoint initiated, waiting for workers.
    InProgress = 1,
    /// All workers confirmed, finalizing.
    Finalizing = 2,
    /// Checkpoint complete and verified.
    Complete = 3,
    /// Checkpoint failed.
    Failed = 4,
    /// Checkpoint timed out.
    Timeout = 5,
}
impl CheckpointState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "CHECKPOINT_STATE_UNSPECIFIED",
            Self::InProgress => "CHECKPOINT_STATE_IN_PROGRESS",
            Self::Finalizing => "CHECKPOINT_STATE_FINALIZING",
            Self::Complete => "CHECKPOINT_STATE_COMPLETE",
            Self::Failed => "CHECKPOINT_STATE_FAILED",
            Self::Timeout => "CHECKPOINT_STATE_TIMEOUT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CHECKPOINT_STATE_UNSPECIFIED" => Some(Self::Unspecified),
            "CHECKPOINT_STATE_IN_PROGRESS" => Some(Self::InProgress),
            "CHECKPOINT_STATE_FINALIZING" => Some(Self::Finalizing),
            "CHECKPOINT_STATE_COMPLETE" => Some(Self::Complete),
            "CHECKPOINT_STATE_FAILED" => Some(Self::Failed),
            "CHECKPOINT_STATE_TIMEOUT" => Some(Self::Timeout),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod coordinator_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// The Coordinator service manages multi-worker distributed training.
    #[derive(Debug, Clone)]
    pub struct CoordinatorServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl CoordinatorServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> CoordinatorServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> CoordinatorServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            CoordinatorServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Register a worker with the coordinator and receive configuration.
        pub async fn register_worker(
            &mut self,
            request: impl tonic::IntoRequest<super::RegisterWorkerRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RegisterWorkerResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/dtr.coordinator.CoordinatorService/RegisterWorker",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "dtr.coordinator.CoordinatorService",
                        "RegisterWorker",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Get shard assignment for a dataset.
        pub async fn get_shard_assignment(
            &mut self,
            request: impl tonic::IntoRequest<super::GetShardAssignmentRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetShardAssignmentResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/dtr.coordinator.CoordinatorService/GetShardAssignment",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "dtr.coordinator.CoordinatorService",
                        "GetShardAssignment",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Report training progress. Bidirectional stream for continuous updates.
        pub async fn report_progress(
            &mut self,
            request: impl tonic::IntoStreamingRequest<Message = super::ProgressReport>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::ProgressAck>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/dtr.coordinator.CoordinatorService/ReportProgress",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "dtr.coordinator.CoordinatorService",
                        "ReportProgress",
                    ),
                );
            self.inner.streaming(req, path, codec).await
        }
        /// Send heartbeat to maintain worker registration.
        pub async fn heartbeat(
            &mut self,
            request: impl tonic::IntoRequest<super::HeartbeatRequest>,
        ) -> std::result::Result<
            tonic::Response<super::HeartbeatResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/dtr.coordinator.CoordinatorService/Heartbeat",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("dtr.coordinator.CoordinatorService", "Heartbeat"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Initiate a distributed checkpoint. Called by any worker or external trigger.
        pub async fn initiate_checkpoint(
            &mut self,
            request: impl tonic::IntoRequest<super::InitiateCheckpointRequest>,
        ) -> std::result::Result<tonic::Response<super::CheckpointPlan>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/dtr.coordinator.CoordinatorService/InitiateCheckpoint",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "dtr.coordinator.CoordinatorService",
                        "InitiateCheckpoint",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Confirm that a worker has completed writing its checkpoint shard.
        pub async fn confirm_checkpoint_shard(
            &mut self,
            request: impl tonic::IntoRequest<super::CheckpointShardConfirmation>,
        ) -> std::result::Result<
            tonic::Response<super::CheckpointShardAck>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/dtr.coordinator.CoordinatorService/ConfirmCheckpointShard",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "dtr.coordinator.CoordinatorService",
                        "ConfirmCheckpointShard",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Query the status of a checkpoint operation.
        pub async fn get_checkpoint_status(
            &mut self,
            request: impl tonic::IntoRequest<super::GetCheckpointStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CheckpointStatus>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/dtr.coordinator.CoordinatorService/GetCheckpointStatus",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "dtr.coordinator.CoordinatorService",
                        "GetCheckpointStatus",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Get current worker status and assignments.
        pub async fn get_worker_status(
            &mut self,
            request: impl tonic::IntoRequest<super::GetWorkerStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::WorkerStatusResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/dtr.coordinator.CoordinatorService/GetWorkerStatus",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "dtr.coordinator.CoordinatorService",
                        "GetWorkerStatus",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Unregister a worker (graceful shutdown).
        pub async fn unregister_worker(
            &mut self,
            request: impl tonic::IntoRequest<super::UnregisterWorkerRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UnregisterWorkerResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/dtr.coordinator.CoordinatorService/UnregisterWorker",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "dtr.coordinator.CoordinatorService",
                        "UnregisterWorker",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod coordinator_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with CoordinatorServiceServer.
    #[async_trait]
    pub trait CoordinatorService: std::marker::Send + std::marker::Sync + 'static {
        /// Register a worker with the coordinator and receive configuration.
        async fn register_worker(
            &self,
            request: tonic::Request<super::RegisterWorkerRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RegisterWorkerResponse>,
            tonic::Status,
        >;
        /// Get shard assignment for a dataset.
        async fn get_shard_assignment(
            &self,
            request: tonic::Request<super::GetShardAssignmentRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetShardAssignmentResponse>,
            tonic::Status,
        >;
        /// Server streaming response type for the ReportProgress method.
        type ReportProgressStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::ProgressAck, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// Report training progress. Bidirectional stream for continuous updates.
        async fn report_progress(
            &self,
            request: tonic::Request<tonic::Streaming<super::ProgressReport>>,
        ) -> std::result::Result<
            tonic::Response<Self::ReportProgressStream>,
            tonic::Status,
        >;
        /// Send heartbeat to maintain worker registration.
        async fn heartbeat(
            &self,
            request: tonic::Request<super::HeartbeatRequest>,
        ) -> std::result::Result<
            tonic::Response<super::HeartbeatResponse>,
            tonic::Status,
        >;
        /// Initiate a distributed checkpoint. Called by any worker or external trigger.
        async fn initiate_checkpoint(
            &self,
            request: tonic::Request<super::InitiateCheckpointRequest>,
        ) -> std::result::Result<tonic::Response<super::CheckpointPlan>, tonic::Status>;
        /// Confirm that a worker has completed writing its checkpoint shard.
        async fn confirm_checkpoint_shard(
            &self,
            request: tonic::Request<super::CheckpointShardConfirmation>,
        ) -> std::result::Result<
            tonic::Response<super::CheckpointShardAck>,
            tonic::Status,
        >;
        /// Query the status of a checkpoint operation.
        async fn get_checkpoint_status(
            &self,
            request: tonic::Request<super::GetCheckpointStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CheckpointStatus>,
            tonic::Status,
        >;
        /// Get current worker status and assignments.
        async fn get_worker_status(
            &self,
            request: tonic::Request<super::GetWorkerStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::WorkerStatusResponse>,
            tonic::Status,
        >;
        /// Unregister a worker (graceful shutdown).
        async fn unregister_worker(
            &self,
            request: tonic::Request<super::UnregisterWorkerRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UnregisterWorkerResponse>,
            tonic::Status,
        >;
    }
    /// The Coordinator service manages multi-worker distributed training.
    #[derive(Debug)]
    pub struct CoordinatorServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> CoordinatorServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for CoordinatorServiceServer<T>
    where
        T: CoordinatorService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/dtr.coordinator.CoordinatorService/RegisterWorker" => {
                    #[allow(non_camel_case_types)]
                    struct RegisterWorkerSvc<T: CoordinatorService>(pub Arc<T>);
                    impl<
                        T: CoordinatorService,
                    > tonic::server::UnaryService<super::RegisterWorkerRequest>
                    for RegisterWorkerSvc<T> {
                        type Response = super::RegisterWorkerResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RegisterWorkerRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as CoordinatorService>::register_worker(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RegisterWorkerSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/dtr.coordinator.CoordinatorService/GetShardAssignment" => {
                    #[allow(non_camel_case_types)]
                    struct GetShardAssignmentSvc<T: CoordinatorService>(pub Arc<T>);
                    impl<
                        T: CoordinatorService,
                    > tonic::server::UnaryService<super::GetShardAssignmentRequest>
                    for GetShardAssignmentSvc<T> {
                        type Response = super::GetShardAssignmentResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetShardAssignmentRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as CoordinatorService>::get_shard_assignment(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetShardAssignmentSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/dtr.coordinator.CoordinatorService/ReportProgress" => {
                    #[allow(non_camel_case_types)]
                    struct ReportProgressSvc<T: CoordinatorService>(pub Arc<T>);
                    impl<
                        T: CoordinatorService,
                    > tonic::server::StreamingService<super::ProgressReport>
                    for ReportProgressSvc<T> {
                        type Response = super::ProgressAck;
                        type ResponseStream = T::ReportProgressStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                tonic::Streaming<super::ProgressReport>,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as CoordinatorService>::report_progress(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ReportProgressSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/dtr.coordinator.CoordinatorService/Heartbeat" => {
                    #[allow(non_camel_case_types)]
                    struct HeartbeatSvc<T: CoordinatorService>(pub Arc<T>);
                    impl<
                        T: CoordinatorService,
                    > tonic::server::UnaryService<super::HeartbeatRequest>
                    for HeartbeatSvc<T> {
                        type Response = super::HeartbeatResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::HeartbeatRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as CoordinatorService>::heartbeat(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = HeartbeatSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/dtr.coordinator.CoordinatorService/InitiateCheckpoint" => {
                    #[allow(non_camel_case_types)]
                    struct InitiateCheckpointSvc<T: CoordinatorService>(pub Arc<T>);
                    impl<
                        T: CoordinatorService,
                    > tonic::server::UnaryService<super::InitiateCheckpointRequest>
                    for InitiateCheckpointSvc<T> {
                        type Response = super::CheckpointPlan;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::InitiateCheckpointRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as CoordinatorService>::initiate_checkpoint(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = InitiateCheckpointSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/dtr.coordinator.CoordinatorService/ConfirmCheckpointShard" => {
                    #[allow(non_camel_case_types)]
                    struct ConfirmCheckpointShardSvc<T: CoordinatorService>(pub Arc<T>);
                    impl<
                        T: CoordinatorService,
                    > tonic::server::UnaryService<super::CheckpointShardConfirmation>
                    for ConfirmCheckpointShardSvc<T> {
                        type Response = super::CheckpointShardAck;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CheckpointShardConfirmation>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as CoordinatorService>::confirm_checkpoint_shard(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ConfirmCheckpointShardSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/dtr.coordinator.CoordinatorService/GetCheckpointStatus" => {
                    #[allow(non_camel_case_types)]
                    struct GetCheckpointStatusSvc<T: CoordinatorService>(pub Arc<T>);
                    impl<
                        T: CoordinatorService,
                    > tonic::server::UnaryService<super::GetCheckpointStatusRequest>
                    for GetCheckpointStatusSvc<T> {
                        type Response = super::CheckpointStatus;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetCheckpointStatusRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as CoordinatorService>::get_checkpoint_status(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetCheckpointStatusSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/dtr.coordinator.CoordinatorService/GetWorkerStatus" => {
                    #[allow(non_camel_case_types)]
                    struct GetWorkerStatusSvc<T: CoordinatorService>(pub Arc<T>);
                    impl<
                        T: CoordinatorService,
                    > tonic::server::UnaryService<super::GetWorkerStatusRequest>
                    for GetWorkerStatusSvc<T> {
                        type Response = super::WorkerStatusResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetWorkerStatusRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as CoordinatorService>::get_worker_status(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetWorkerStatusSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/dtr.coordinator.CoordinatorService/UnregisterWorker" => {
                    #[allow(non_camel_case_types)]
                    struct UnregisterWorkerSvc<T: CoordinatorService>(pub Arc<T>);
                    impl<
                        T: CoordinatorService,
                    > tonic::server::UnaryService<super::UnregisterWorkerRequest>
                    for UnregisterWorkerSvc<T> {
                        type Response = super::UnregisterWorkerResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UnregisterWorkerRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as CoordinatorService>::unregister_worker(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UnregisterWorkerSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for CoordinatorServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "dtr.coordinator.CoordinatorService";
    impl<T> tonic::server::NamedService for CoordinatorServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
